config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:create]

  resources :comments, only: [:create]


  get '/blog' => 'posts#index', as: :posts
  get '/blog/:id' => 'posts#show', as: :post

  resources :subscribers, only: [:create]
  resources :projects, only: [:new, :create]
  resources :remotes, only: [:new, :create]

  namespace :admin do
    resources :users
    resources :team_members
    resources :projects
    resources :contacts
    resources :posts
    resources :tags
    resources :leads
    resources :comments
    resources :remotes

    root to: "team_members#index"
  end

  root 'pages#home'
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/pages/_home/_blog-posts.slim
#blog-posts
  .title
    | blog_
    span red
    | rocket
  .row.cards-row
    - @posts.each do |post|
      .col.l4.s12
        .card
          .card-image
            = link_to post do
              = image_tag post.header.url, alt: post.title, title: post.title
          .card-content
            span.tag-title
              = link_to post.tag.title, "?filter=#{post.tag.id}"
            p.post-title
              = link_to post.title, post
          .card-action
            .row.no-margin
              .col.s3.writer-image style="background-image: url(' #{post.team_member.photo.url} ');"
              .col.l9
                .writer-name
                  = post.team_member.name
                span.post-date
                  = post.created_at.strftime("%d/%m/%Y às %H:%M")
  div.center
    = link_to t("blog.see-more"), "/blog", class: "see-more"

app/views/pages/_home/_call-to-action.slim
div#call-to-action
  .title
    = t("call-to-action.title")
  .flex-button-row
    = link_to t("call-to-action.start-project"), new_project_path, class: "start-project"
    = link_to t("call-to-action.be-prolancer"), new_remote_path, class: "be-prolancer"

app/views/pages/_home/_how-it-works.slim
div#how-it-works
  div.title
    = t("how-it-works.title")
  div.row.steps-row
    div.col.l4.s12
      .steps-img
        = image_tag("icons/svg/icone_sua-ideia.svg")
      .steps-info
        .col-title
          = t("how-it-works.steps.first.title")
        .description.fira-sans
          = t("how-it-works.steps.first.description")
    div.col.l4.s12
      .steps-img
        = image_tag("icons/svg/icone_proposta.svg")
      .steps-info
        .col-title
          = t("how-it-works.steps.second.title")
        .description.fira-sans
          = t("how-it-works.steps.second.description")
    div.col.l4.s12
      .steps-img
        = image_tag("icons/svg/icone_foguete.svg")
      .steps-info
        .col-title
          = t("how-it-works.steps.third.title")
        .description.fira-sans
          = t("how-it-works.steps.third.description")
  p.project-button.center
    = link_to t('intro.start-project'), new_project_path, class: "start-project"

app/views/pages/_home/_intro.html.slim
section#intro
  = render 'shared/header'
  .container.center
    div.center-align.white-text.header
      = t('intro.turn-ideas-reality')
    h1.center-align.redrocket-text-color.subheader
      = t('intro.what-we-do')
    p.project-button
      = link_to t('intro.start-project'), new_project_path, class: "start-project"

app/views/pages/_home/_portfolio.html.slim
div#portfolio
  .section
    .row
      .col.l6.offset-l1.s12.center.hide-on-large-only
        = image_tag("imgs_movpak.png")
      .col.l5.s12
        .type-of-project
          = t("portfolio.first.type")
        .project-title
          = t("portfolio.first.title")
        .project-description.fira-sans
          = t("portfolio.first.description")
        .go-to-project
          = link_to t("portfolio.call-to-action"), t("portfolio.first.url"), target: "_blank"
      .col.l6.s12.center.hide-on-med-and-down
        = image_tag("imgs_movpak.png")
  .section.odd
    .row
      .col.l6.s12.center
        = image_tag("imgs_learny.png")
      .col.l5.offset-l1.s12
        .type-of-project
          = t("portfolio.second.type")
        .project-title
          = t("portfolio.second.title")
        .project-description.fira-sans
          = t("portfolio.second.description")
        .go-to-project
          = link_to t("portfolio.call-to-action"), t("portfolio.second.url"), target: "_blank"
  .section
    .row
      .col.l6.offset-l1.s12.center.hide-on-large-only
        = image_tag("imgs_caixa-da-cegonha.png")
      .col.l5.s12
        .type-of-project
          = t("portfolio.third.type")
        .project-title
          = t("portfolio.third.title")
        .project-description.fira-sans
          = t("portfolio.third.description")
        .go-to-project
          = link_to t("portfolio.call-to-action"), t("portfolio.third.url"), target: "_blank"
      .col.l6.s12.center.hide-on-med-and-down
        = image_tag("imgs_caixa-da-cegonha.png")

app/views/pages/_home/_technologies.html.slim
div#technologies.white-text
  div.section-title
    = t("technologies.title")
  p.fira-sans.center.section-description
    = t("technologies.description")
  .flex-image-row
    = image_tag("icons/svg/icone_rails.svg")
    = image_tag("icons/svg/icone_angular.svg")
    = image_tag("icons/svg/icone_ionic.svg")
    = image_tag("icons/svg/icone_react.svg")

app/views/pages/_home/_testimonials.html.slim
div#testimonials
  div.section-header
    = t("testimonials.title")
  div.row
    div.col.l6.s12.m6.testimonials-col data-id = 0
      div.card.testimonials-card
        = image_tag("icons/svg/icon_citacao_red.svg", class: "quote-image")
        = image_tag( t("testimonials.first.image") , class: "circle responsive-img hide-on-small-only")
        p.roboto
          = t("testimonials.first.text")
        h5
          = t("testimonials.first.client-name") + ", "
          span = t("testimonials.first.project-name")
    div.col.l6.s12.m6.testimonials-col data-id = 1
      div.card.testimonials-card
        = image_tag("icons/svg/icon_citacao_red.svg", class: "quote-image")
        = image_tag( t("testimonials.second.image") , class: "circle responsive-img hide-on-small-only")
        p.roboto
          = t("testimonials.second.text")
        h5
          = t("testimonials.second.client-name") + ", "
          span = t("testimonials.second.project-name")
  div.indicators-row.hide-on-small-only

app/views/pages/_home/_what_we_do.html.slim
div#what-we-do
  div#what-we-do-content
    div.section-header = t("what-we-do.title")
    div
      div.row
        div.col.l4.s12
          div.card
            div.card-content.center
              = image_tag("icons/svg/icone_aplicativos.svg")
              h3.card-title
                = t("what-we-do.app-card.title")
              p.description.fira-sans
                = t("what-we-do.app-card.description")
              div.information
                = t("what-we-do.app-card.price")
              div.information
                = t("what-we-do.app-card.time")
        div.col.l4.s12
          div.card
            div.card-content.center
              = image_tag("icons/svg/icone_lojas-virtuais.svg")
              h3.card-title
                = t("what-we-do.ecommerces-card.title")
              p.description.fira-sans
                = t("what-we-do.ecommerces-card.description")
              div.information
                = t("what-we-do.ecommerces-card.price")
              div.information
                = t("what-we-do.ecommerces-card.time")
        div.col.l4.s12
          div.card
            div.card-content.center
              = image_tag("icons/svg/icone_sites.svg")
              h3.card-title
                = t("what-we-do.sites-card.title")
              p.description.fira-sans
                = t("what-we-do.sites-card.description")
              div.information
                = t("what-we-do.sites-card.price")
              div.information
                = t("what-we-do.sites-card.time")