config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:create]

  resources :comments, only: [:create]


  get '/blog' => 'posts#index', as: :posts
  get '/blog/:id' => 'posts#show', as: :post

  resources :subscribers, only: [:create]
  resources :projects, only: [:new, :create]
  resources :remotes, only: [:new, :create]

  namespace :admin do
    resources :users
    resources :team_members
    resources :projects
    resources :contacts
    resources :posts
    resources :tags
    resources :leads
    resources :comments
    resources :remotes

    root to: "team_members#index"
  end

  root 'pages#home'
end

app/models/remote.rb
class Remote < ApplicationRecord
end

app/controllers/admin/remotes_controller.rb
module Admin
  class RemotesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Project.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Project.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/remotes_controller.rb
class RemotesController < ApplicationController
  before_action :prepare_meta_tags, if: "request.get?"

  def new
    @remote = Remote.new
  end

  def create
    @remote = Remote.new(remote_params)

    respond_to do |format|
      if @remote.save
        format.html { redirect_to root_path, notice: t("remotes.create.success") }
      else
        format.html { redirect_to root_path }
      end
    end
  end

  private
    def remote_params
      params.permit(:name, :email, :remote_type, :tecnologies, :github, :behance, :links, :about, :how_you_met_red)
    end
end

app/views/remotes/_new/_form.html.slim
#form
  div.row
    div.col.l6.offset-l3.s12
      .title
        = t("remotes.form.title")
      .description
        = t("remotes.form.description")
  div.row
    div.col.l6.offset-l3.s12
      = form_tag(remotes_path)
        label for="name"
          = t("remotes.form.fields.name.label")
        div.input-field
          = text_field_tag 'name'

        label for="email"
          = t("remotes.form.fields.email.label")
        div.input-field
          = text_field_tag 'email'

        label for="remote_type"
          = t("remotes.form.fields.remote_type.label")
        div.input-field
          = select_tag "remote_type", options_for_select(["Back End", "Front End", "Designer"])

        label for="tecnologies"
          = t("remotes.form.fields.tecnologies.label")
        div.input-field
          = text_field_tag 'tecnologies'

        label for="github"
          = t("remotes.form.fields.github.label")
        div.input-field
          = text_field_tag 'github'

        label for="behance"
          = t("remotes.form.fields.behance.label")
        div.input-field
          = text_field_tag 'behance'

        label for="links"
          = t("remotes.form.fields.links.label")
        div.input-field
          = text_area_tag 'links', nil, placeholder: "#{t("remotes.form.fields.links.placeholder")}", class: "materialize-textarea"

        label for="about"
          = t("remotes.form.fields.about.label")
        div.input-field
          = text_area_tag 'about', nil, placeholder: "#{t("remotes.form.fields.about.placeholder")}", class: "materialize-textarea"

        label for="how_you_met_red"
          = t("remotes.form.fields.how_you_met_red.label")
        div.input-field
          = select_tag "how_you_met_red", options_for_select([\
          "#{t('remotes.form.fields.how_you_met_red.options.internet')}",
          "#{t('remotes.form.fields.how_you_met_red.options.referral')}",
          "#{t('remotes.form.fields.how_you_met_red.options.facebook')}",
          "#{t('remotes.form.fields.how_you_met_red.options.instagram')}",
          "#{t('remotes.form.fields.how_you_met_red.options.other')}"])

        .center
          button.send-form
            | ENVIAR

app/views/remotes/_new/_how-it-works.html.slim
div#how-it-works
  div.title
    = t("how-it-works.title")
  div.row.steps-row
    div.col.l4.s12
      .steps-img
        = image_tag("icons/svg/icone_cadastre-se.svg")
      .steps-info
        .col-title
          = t("remotes.how-it-works.first.title")
        .description
          = t("remotes.how-it-works.first.description")
    div.col.l4.s12
      .steps-img
        = image_tag("icons/svg/icone_convites.svg")
      .steps-info
        .col-title
          = t("remotes.how-it-works.second.title")
        .description
          = t("remotes.how-it-works.second.description")
    div.col.l4.s12
      .steps-img
        = image_tag("icons/svg/icone_pagamento.svg")
      .steps-info
        .col-title
          = t("remotes.how-it-works.third.title")
        .description
          = t("remotes.how-it-works.third.description")